# Generated by Django 4.1.6 on 2023-02-07 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Product_name', models.CharField(max_length=30)),
                ('Product_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('Price', models.IntegerField(max_length=4)),
                ('Id', models.UUIDField(default=uuid.UUID('b6051016-4922-4118-8eda-9c98ac0ee948'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
