# Generated by Django 4.1.6 on 2023-02-08 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0002_product_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('d5ca0fc7-8310-4d5c-8e39-7910285c6317'), editable=False, primary_key=True, serialize=False),
        ),
    ]
