# Generated by Django 4.1.6 on 2023-02-08 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('cc5c616f-b942-4bd9-8fd8-5c1823527b0e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
