# Generated by Django 4.1.6 on 2023-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0004_alter_product_id_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
